version: 2

models:
  - name: enr_google_search_console_by_property
    description: "Enriched table with google search console date on property level"
    columns:
    - name: gsc_property
      description: "The domain name of the search results"
      tests:
        - not_null

    - name: search_date
      description: "The date on wich the search was executed"
      tests:
        - not_null

    - name: search_date_key
      description: "The key to the date dimension for the search_date column"
      tests:
        - not_null

    - name: clicks
      description: "The number of clicks on search results"
      tests:
        - not_null

    - name: impressions
      description: "The number of impressions or how many times this page showed up in search results"
      tests:
        - not_null

    - name: results_position
      description: "The (average) position in the search results"
      tests:
        - dbt_utils.expression_is_true:
            expression: '>= 1'
        - not_null

    - name: vg
      description: "The Miele VG to which the search results belong"
      tests:
        - not_null

  - name: enr_google_search_console_by_query
    description: "Enriched table with google search console date on query level"
    columns:
    - name: gsc_property
      description: "The domain name for the metrics"
      tests:
        - not_null

    - name: query
      description: "The search query entered in google search"
      tests:
        - not_null

    - name: query_type
      description: "The search query type entered in google search (Branded / Non-Branded)"
      tests:
        - not_null

    - name: search_date
      description: "The date on wich the search was executed"
      tests:
        - not_null

    - name: search_date_key
      description: "The key to the date dimension for the search_date column"
      tests:
        - not_null

    - name: clicks
      description: "The number of clicks on search results"
      tests:
        - not_null

    - name: impressions
      description: "The number of impressions or how many times this page showed up in search results"
      tests:
        - not_null

    - name: results_position
      description: "The (average) position in the search results"
      tests:
        - dbt_utils.expression_is_true:
            expression: '>= 1'
        - not_null

    - name: vg
      description: "The Miele VG to which the search results belong"
      tests:
        - not_null

  - name: enr_google_search_console
    description: "Enriched table with google search console data including all dimensions"
    columns:
      - name: gsc_property
        description: "The domain name for the metrics"
        tests:
          - not_null

      - name: query
        description: "The search query entered in google search"
        tests:
          - not_null

      - name: query_type
        description: "The search query type entered in google search (Branded / Non-Branded)"
        tests:
          - not_null

      - name: page
        description: "The page of the Miele website for the search results"
        tests:
          - not_null

      - name: page_type
        description: "The page type of the Miele website for the search results"
        tests:
          - not_null

      - name: page_cleaned
        description: "The cleaned page of the Miele website for the search results"
        tests:
          - not_null

      - name: host_name
        description: "The host name (Miele website name) for the search results"
        tests:
          - not_null

      - name: page_url
        description: "The page url of the Miele website for the search results"
        tests:
          - not_null

      - name: product_pim_code
        description: "The PIM code of the product if a product page and if available"

      - name: product_name
        description: "The name of the product if a product page and if available"

      - name: clicks
        description: "The number of clicks on search results"
        tests:
          - not_null

      - name: impressions
        description: "The number of impressions or how many times this page showed up in search results"
        tests:
          - not_null

      - name: results_position
        description: "The (average) position in the search results"
        tests:
          - dbt_utils.expression_is_true:
              expression: '>= 1'
          - not_null
    
      - name: gsc_country_code
        description: "The country code of the country from which the search was executed"
        tests:
          - not_null

      - name: country_name
        description: "The country name (ISO-3601) of the country from which the search was executed"
        tests:
          - not_null

      - name: country_code_alpha2
        description: "The country identifier (ISO-3601 alpha2) of the country from which the search was executed"
        tests:
          - not_null

      - name: country_code_alpha3
        description: "The country identifier (ISO-3601 alpha3) of the metrics"
        tests:
          - not_null

      - name: search_date
        description: "The date on wich the search was executed"
        tests:
          - not_null

      - name: search_date_key
        description: "The key to the date dimension for the search_date column"
        tests:
          - not_null

      - name: device
        description: "The device on which the search was executed"
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['DESKTOP', 'MOBILE', 'TABLET']
              quote_values: true
          - not_null

      - name: vg
        description: "The Miele VG to which the search results belong"
        tests:
          - not_null

