version: 2

models:
  - name: fact_doms_event_hit_product_ua_bq
    columns:
      - name: session_key
        tests:
          - relationships:
              to: ref('dim_doms_session_ua_bq')
              field: session_key     
      - name: hit_key
        tests:
          - relationships:
              to: ref('dim_doms_hit_ua_bq')
              field: hit_key
      - name: event_key
        tests:
          - relationships:
              to: ref('dim_doms_event_ua_bq')
              field: event_key
      - name: page_key
        tests:
          - relationships:
              to: ref('dim_doms_page_ua_bq')
              field: page_key
      - name: product_ua_bq_key
        tests:
          - relationships:
              to: ref('dim_doms_product_ua_bq')
              field: product_ua_bq_key

  - name: fact_doms_event_hit_ua_bq
    columns:
      - name: session_key
        tests:
          - relationships:
              to: ref('dim_doms_session_ua_bq')
              field: session_key    
      - name: hit_key
        tests:
          - relationships:
              to: ref('dim_doms_hit_ua_bq')
              field: hit_key
      - name: event_key
        tests:
          - relationships:
              to: ref('dim_doms_event_ua_bq')
              field: event_key

  - name: fact_doms_experiment_ua_bq
    columns:
      - name: session_key
        tests:
          - relationships:
              to: ref('dim_doms_session_ua_bq')
              field: session_key    
      - name: hit_key
        tests:
          - relationships:
              to: ref('dim_doms_hit_ua_bq')
              field: hit_key
      - name: experiment_key
        tests:
          - relationships:
              to: ref('dim_doms_experiment_ua_bq')
              field: experiment_key

  - name: fact_doms_order_ua_bq
    columns:
      - name: order_key
      - name: hit_key
        tests:
          - relationships:
              to: ref('dim_doms_hit_ua_bq')
              field: hit_key
      - name: hit_time_key
      - name: traffic_source_key
        tests:
          - relationships:
              to: ref('dim_doms_traffic_source_ua_bq')
              field: traffic_source_key
      - name: device_key
        tests:
          - relationships:
              to: ref('dim_doms_device_ua_bq')
              field: device_key
      - name: session_key
        tests:
          - relationships:
              to: ref('dim_doms_session_ua_bq')
              field: session_key

  - name: fact_doms_orderline_ua_bq
    columns:
      - name: session_key
        tests:
          - relationships:
              to: ref('dim_doms_session_ua_bq')
              field: session_key    
      - name: hit_key
        tests:
          - relationships:
              to: ref('dim_doms_hit_ua_bq')
              field: hit_key
      - name: traffic_source_key
        tests:
          - relationships:
              to: ref('dim_doms_traffic_source_ua_bq')
              field: traffic_source_key
      - name: device_key
        tests:
          - relationships:
              to: ref('dim_doms_device_ua_bq')
              field: device_key
      - name: hit_time_key
      - name: order_key
      - name: product_ua_bq_key
        tests:
          - relationships:
              to: ref('dim_doms_product_ua_bq')
              field: product_ua_bq_key

  - name: fact_doms_page_hit_ua_bq
    columns:
      - name: hit_key
        tests:
          - relationships:
              to: ref('dim_doms_hit_ua_bq')
              field: hit_key
      - name: page_key
        tests:
          - relationships:
              to: ref('dim_doms_page_ua_bq')
              field: page_key
      - name: session_key
        tests:
          - relationships:
              to: ref('dim_doms_session_ua_bq')
              field: session_key    
      - name: traffic_source_key
        tests:
          - relationships:
              to: ref('dim_doms_traffic_source_ua_bq')
              field: traffic_source_key   
      - name: device_key
        tests:
          - relationships:
              to: ref('dim_doms_device_ua_bq')
              field: device_key

  - name: fact_doms_session_ua_bq
    columns: 
      - name: session_key
        tests:
          - relationships:
              to: ref('dim_doms_session_ua_bq')
              field: session_key
      - name: device_key
        tests:
          - relationships:
              to: ref('dim_doms_device_ua_bq')
              field: device_key
      - name: traffic_source_key
        tests:
          - relationships:
              to: ref('dim_doms_traffic_source_ua_bq')
              field: traffic_source_key