MXA_DI:
  outputs:
    dev:
      host: "{{ env_var('DATABRICKS_HOST_DBT') }}"
      http_path: "{{ env_var('DATABRICKS_ENDPOINT_DBT') }}"
      schema: "{{ env_var('DBT_USER_SCHEMA') }}"
      threads: 4
      token: "{{ env_var('DATABRICKS_TOKEN_DBT') }}"
      type: databricks
    prod:
      host: "{{ env_var('DATABRICKS_HOST_DBT') }}"
      http_path: "{{ env_var('DATABRICKS_ENDPOINT_DBT') }}"
      schema: mxa_di
      threads: 4
      token: "{{ env_var('DATABRICKS_TOKEN_DBT') }}"
      type: databricks
  target: dev
elementary:
  outputs:
    dev:
      type: "databricks"
      host: "{{ env_var('DATABRICKS_HOST_DBT') }}"
      http_path: "{{ env_var('DATABRICKS_ENDPOINT_DBT') }}"
      schema: "{{ env_var('DBT_USER_SCHEMA') }}_elementary"
      token: "{{ env_var('DATABRICKS_TOKEN_DBT') }}"
      threads: 4
    prod:
      host: "{{ env_var('DATABRICKS_HOST_DBT') }}"
      http_path: "{{ env_var('DATABRICKS_ENDPOINT_DBT') }}"
      schema: mxa_di_elementary
      threads: 4
      token: "{{ env_var('DATABRICKS_TOKEN_DBT') }}"
      type: databricks
  target: dev