version: 2

models:
  - name: dim_sapbw_billing_type
    description: ""
    columns:
      - name: reporting_unit_code
        description: ""

      - name: billing_type_code
        description: ""

      - name: text_short
        description: ""

      - name: text_medium
        description: ""

      - name: text_long
        description: ""

      - name: meta_insert_ts
        description: ""

  - name: dim_sapbw_buying_group
    description: ""
    columns:
      - name: reporting_unit_code
        description: ""

      - name: buying_group_code
        description: ""

      - name: text_short
        description: ""

      - name: text_medium
        description: ""

      - name: text_long
        description: ""

      - name: meta_insert_ts
        description: ""

  - name: dim_sapbw_campaign
    description: ""
    columns:
      - name: reporting_unit_code
        description: ""

      - name: campaign_code
        description: ""

      - name: text_short
        description: ""

      - name: text_medium
        description: ""

      - name: text_long
        description: ""

      - name: meta_insert_ts
        description: ""

  - name: dim_sapbw_crm_transaction_type
    description: ""
    columns:
      - name: crm_transaction_type_code
        description: ""
        tests:
          - unique

      - name: text_short
        description: ""

      - name: text_medium
        description: ""

      - name: text_long
        description: ""

      - name: meta_insert_ts
        description: ""

  - name: dim_sapbw_distribution_channel
    description: ""
    columns:
      - name: distribution_channel_code
        description: ""
        tests:
          - unique

      - name: text_short
        description: ""

      - name: meta_insert_ts
        description: ""

  - name: dim_sapbw_division_sales
    description: ""
    columns:
      - name: reporting_unit_code
        description: ""

      - name: division_sales_code
        description: ""

      - name: text_short
        description: ""

      - name: text_medium
        description: ""

      - name: text_long
        description: ""

      - name: meta_insert_ts
        description: ""

  - name: dim_sapbw_material
    description: ""
    columns:
      - name: material_code
        description: ""
        tests:
          - unique

      - name: text_short
        description: ""

      - name: text_medium
        description: ""

      - name: text_long
        description: ""

      - name: meta_insert_ts
        description: ""

  - name: dim_sapbw_org_consumer_classification_chain
    description: ""
    columns:
      - name: org_consumer_classification_chain_code
        description: ""
        tests:
          - unique

      - name: text_short
        description: ""

      - name: text_medium
        description: ""

      - name: text_long
        description: ""

      - name: meta_insert_ts
        description: ""

  - name: dim_sapbw_org_unit
    description: ""
    columns:
      - name: org_unit
        description: ""

      - name: text_short
        description: ""

      - name: text_medium
        description: ""

      - name: text_long
        description: ""

      - name: meta_insert_ts
        description: ""

  - name: dim_sapbw_reporting_unit
    description: ""
    columns:
      - name: reporting_unit_code
        description: ""
        tests:
          - unique

      - name: text_short
        description: ""

      - name: text_medium
        description: ""

      - name: text_long
        description: ""

      - name: meta_insert_ts
        description: ""

  - name: dim_sapbw_sales_org
    description: ""
    columns:
      - name: sales_org
        description: ""
        tests:
          - unique

      - name: text_short
        description: ""

      - name: text_medium
        description: ""

      - name: text_long
        description: ""

      - name: meta_insert_ts
        description: ""

  - name: dim_sapbw_soldto_business_partner_type
    description: ""
    columns:
      - name: reporting_unit_code
        description: ""

      - name: soldto_business_partner_type_code
        description: ""

      - name: text_short
        description: ""

      - name: text_medium
        description: ""

      - name: text_long
        description: ""

      - name: meta_insert_ts
        description: ""

  - name: dim_sapbw_soldto_industry
    description: ""
    columns:
      - name: customer_soldto_industry_miele_code
        description: ""
        tests:
          - unique

      - name: text_short
        description: ""

      - name: text_medium
        description: ""

      - name: text_long
        description: ""

      - name: meta_insert_ts
        description: ""
        
  - name: dim_sapbw_n3_cust_grp3_miele_club
    description: "BW Customer Group 3 Miele Club dimension from Next3 (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  
        
  - name: dim_sapbw_n3_dealer_agent
    description: "BW Dealer Agent dimension from Next3 - dependent on the reporting unit (Seed Data)"
    columns:
      - name: rep_unit_code
        description: "Code of the Reporting Unit"

      - name: dealer_agent_code
        description: "Code for the Dealer/Agent"

      - name: dealer_agent_desc
        description: "Description for the Dealer/Agent"    

  - name: dim_sapbw_n3_entry_channel
    description: "BW Entry Channel dimension from Next3 (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_n3_industry_miele
    description: "BW SoldTo Industry Miele Codification dimension from Next3 (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_n3_industry_nace
    description: "BW SoldTo Industry NACE Codification dimension from Next3 (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_n3_int_account_customer
    description: "BW SoldTo Intenrational Account Customer dimension from Next3 - dependent on the reporting unit (Seed Data)"
    columns:
      - name: rep_unit_code
        description: "Code of the Reporting Unit"

      - name: int_acct_customer_code
        description: "Code of the International Account Customer attribute"  

      - name: int_acct_customer_desc
        description: "Description of the International Account Customer attribute"          

  - name: dim_sapbw_n3_item_category
    description: "BW Item Category dimension from Next3 (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_n3_reason_rejection
    description: "BW Order Reason Rejection dimension from Next3 (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_n3_status_delivered
    description: "BW Order Status Delivered dimension from Next3 (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_n3_status_order_creation
    description: "BW Order Status Creation dimension from Next3 (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_n3_status_quality
    description: "BW Order Status Quality dimension from Next3 (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_vgd_3_20_sold_to_cust_assoc_group
    description: "BW SoldTo Customer Association Group dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_vgd_3_31_sold_to_industry
    description: "BW SoldTo Industry dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"          

  - name: dim_sapbw_vgd_3_53_cust_account_group
    description: "BW Customer Account Group dimension from VGD (Seed Data)"
    columns:
      - name: client_number
        description: "Client Number (generic for Miele)"

      - name: language_key
        description: "Code for the language of the data (for VGD should be D)"  

      - name: customer_account_group_code
        description: "Code for the account group"  

      - name: account_group_name
        description: "Description for the account group"  

      - name: flag_relevant
        description: "Indicates if the code is relevant or not"  

  - name: dim_sapbw_vgd_3_55_customer_group
    description: "BW Customer Group dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_vgd_4_06_sales_group
    description: "BW Sales Group dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_vgd_6_04_document_type
    description: "BW Document Type dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_vgd_6_07_status_delivered
    description: "BW Order Status Delivered dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_vgd_6_08_document_category
    description: "BW Document Category dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"  

  - name: dim_sapbw_vgd_6_09_campaign
    description: "BW Campaign dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"

  - name: dim_sapbw_vgd_6_22_billing_type
    description: "BW Billing Type dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"

  - name: dim_sapbw_vgd_6_23_item_category
    description: "BW Item Category dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"

  - name: dim_sapbw_vgd_6_30_version
    description: "BW Version dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"

  - name: dim_sapbw_vgd_7_01_distribution_channel
    description: "BW Distribution CHannel dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"

  - name: dim_sapbw_vgd_7_04_order_reason
    description: "BW Order Reason dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"

  - name: dim_sapbw_vgd_7_05_reason_rejection
    description: "BW Order reason rejection dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"

  - name: dim_sapbw_vgd_7_07_program_series
    description: "BW Program series dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"

  - name: dim_sapbw_vgd_7_08_sd_order_type
    description: "BW Sales Document Order Type dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"

  - name: dim_sapbw_vgd_7_99_division
    description: "BW Division dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"

  - name: dim_sapbw_vgd_9_03_status_rejection
    description: "BW Order Status Rejection dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"

  - name: dim_sapbw_vgd_9_20_value_type
    description: "BW Value Type dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"

  - name: dim_sapbw_vgd_9_99_valuation_view
    description: "BW Valuation View dimension from VGD (Seed Data)"
    columns:
      - name: member_code
        description: "Code for the member"

      - name: member_desc
        description: "Description for the member"

