version: 2

models:
  - name: professional_leads_quotes
    description: table containing all unique sales_quotes from sap c4c professional leads
    columns:
      - name: '`Sales Quote ID`'
        description: PK
        tests:
          - unique
      - name: '`Lead ID`'
        description: FK
        tests:
           - relationships:
              to: ref('professional_leads')
              field: '`Lead ID`'
              config:
                severity: warn

  - name: professional_leads_sales_orders
    description: all unique sales orders that resulted from sap c4c professional leads    
    columns:
      - name: '`Sales Order`'
        description: PK
        tests:
          - unique
      - name: '`Lead ID`'
        description: The lead that resulted in this sales order
      - name: '`Sales Quote ID`'
        description: FK, sales quote that resulted in this order
        tests:
           - relationships:
              to: ref('professional_leads_quotes')
              field: '`Sales Quote ID`'
              config:
                severity: warn

  - name: professional_leads
    description: single row per professional lead from sap C4C.
    columns:
      - name: '`Lead ID`'
        description: PK
        tests:
          - unique