models:
  - name: rpt_dim_ga4_doms_device
    description: https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cdevice
  - name: rpt_dim_ga4_doms_ga_campaign
    description: unique ga campaign IDs with corresponding name
  - name: rpt_dim_ga4_doms_ga_item
    description: table with the unique Google Analytics Miele items/products and characteristics - https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Citems
  - name: rpt_dim_ga4_doms_geo
    description: table with the unique geo locations from GA, https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cgeo
  - name: rpt_dim_ga4_doms_product_master_mapping
    description:  Mapping table to the the Miele Product Master that is populated from PIM. dwh.dim_product_master_pim
  - name: rpt_dim_ga4_doms_session
    description: table with a record for every unique session
  - name: rpt_dim_ga4_doms_traffic_source
    description: unique session level source/medium and custom channel grouping
  - name: rpt_fct_ga4_doms_order
    description: contains all purchase events, https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cecommerce
  - name: rpt_fct_ga4_doms_orderline
    description: contains the items included in a purchase event
  - name: rpt_fct_ga4_doms_session
    description: Contains all unique session + session metrics
  - name: rpt_fct_ga4_doms_pageview
    description: Contains all pageview events