version: 2

models:
  - name: google_ads_keyword
    description: "Enriched table with google ads Keyword data"
    columns:
      - name: date_key
        description: "key for the date dimension"
        tests:
          - not_null

      - name: device_key
        description: "key for the device dimension"
        tests:
          - not_null

      - name: account_key
        description: "The account/customer id for google ads name for the metrics"
        tests:
          - not_null

      - name: campaign_key
        description: "The the campaign_id of the campaign"
        tests:
          - not_null

      - name: adgroup_key
        description: "The adgroup_id of google adgroup"
        tests:
          - not_null

      - name: keyword_key
        description: "The key word in the google ads"
        tests:
          - not_null
      