models:
  - name: enr_ga4_domestic_collected_traffic_source
    description: granularity = event, column description = https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Ccollected-traffic-source
    columns:
      - name: event_key
        description: FK
        tests:
          - not_null
          - relationships:
              to: ref('enr_ga4_domestic_events')
              field: event_key
      - name: collected_traffic_source_key
        description: Surrogate Key identifying the unique combination of 'manual_campaign_id', 'manual_campaign_name', 'manual_source', 'manual_medium', 'manual_term', 'gclid', 'dclid', 'srsltid'

  - name: enr_ga4_domestic_device
    description: granularity = event, column description = https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cdevice
    columns:
      - name: event_key
        description: FK
        tests:
          - not_null
          - relationships:
              to: ref('enr_ga4_domestic_events')
              field: event_key
      - name: device_key
        description: Surrogate Key identifying the unique combination of 'device_category', 'mobile_brand_name', 'mobile_model_name', 'operating_system', 'operating_system_version', 'device_language', 'mobile_marketing_name'

  - name: enr_ga4_domestic_ecommerce
    description: granularity = event, column description = https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cecommerce
    columns:
      - name: event_key
        description: FK
        tests:
          - not_null
          - relationships:
              to: ref('enr_ga4_domestic_events')
              field: event_key
      - name: transaction_id_rownum
        description: rownumber to filter duplicate transactions. value 1 is unique.

  - name: enr_ga4_domestic_event_parameters
    description: granularity = event parameter, column description = https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cevent
    columns:
      - name: event_key
        description: FK, PK = event_key + event_parameter
        tests:
          - not_null
          - relationships:
              to: ref('enr_ga4_domestic_events')
              field: event_key
      - name: param_value_string
        description: This field is only filled if the value has dat type string
      - name: param_value_int
        description: This field is only filled if the value has dat type integer
      - name: param_value_double
        description: This field is only filled if the value has dat type double
      - name: parameter_value
        description: Coalesce of the parameter value fields, cast to a string.
      - name: vg
        description: Miele vg tied to the GA property
      - name: property_id
        description: GA property ID

  - name: enr_ga4_domestic_events
    description: granularity = event, column description = https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cevent
    columns:
      - name: event_key
        description: PK
        tests:
          - unique
          - not_null
      - name: client_key
        description: Surrogate Key identifying the unique combination of 'user_pseudo_id', 'stream_id'
      - name: session_key
        description: Surrogate Key identifying the unique combination of 'user_pseudo_id', 'stream_id', 'parameter_value'
      - name: vg
        description: Miele vg tied to the GA property
      - name: property_id
        description: GA property ID

  - name: enr_ga4_domestic_geo
    description: granularity = event, column description = https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cgeo
    columns:
      - name: event_key
        description: FK
        tests:
          - not_null
          - relationships:
              to: ref('enr_ga4_domestic_events')
              field: event_key
      - name: geo_key
        description: Surrogate Key identifying the unique combination of all fields in this geo table.

  - name: enr_ga4_domestic_items
    description: granularity = events x items, column description = https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Citems
    columns:
      - name: event_key
        description: FK, PK = event_key + item_key
        tests:
          - not_null
          - relationships:
              to: ref('enr_ga4_domestic_events')
              field: event_key
      - name: item_key 
        description: Surrogate Key identifying the unique combination of id, name, brand, variant and all category columns

  - name: enr_ga4_domestic_user_traffic_source
    description: granularity = event, column description = https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Ctraffic-source
    columns:
      - name: event_key
        tests:
          - not_null
          - relationships:
              to: ref('enr_ga4_domestic_events')
              field: event_key
      - name: user_traffic_source_key
        description: Surrogate key identifying the unique combination of 'traffic_name', 'traffic_medium', 'traffic_source'
          
  - name: enr_ga4_domestic_user_properties
    description: Holds the most recent version of the user properties for a unique 'client', column description = https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cuser
    columns:
      - name: client_key
        description: Surrogate Key identifying the unique combination of 'user_pseudo_id' and 'stream_id', PK
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('enr_ga4_domestic_events')
              field: client_key
              