models:
  - name: dim_ga4_doms_device
    description: https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cdevice
    columns:
      - name: device_key
        description: PK, unique combination of category, brand_name, model_name, os, os_version, language, marketing_name
        tests:
          - not_null
          - unique
  - name: dim_ga4_doms_ga_campaign
    description: tabel containing all unique campaign IDs from Google Analytics
    columns: 
      - name: ga_campaign_key
        description: PK
        tests:
          - not_null
          - unique
      - name: campaign_id
        description: Campaign IDs from collected traffic source in GA. Is assigned to a session based on the attribution model. Value is the UTM_ID generated for the campaign.
        tests: 
          - unique
      - name: campaign_name
        description: This field is populated with the last provided name for the corresponding campaign ID.

  - name: dim_ga4_doms_ga_item
    description: table with the unique Google Analytics Miele items/products and characteristics - https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Citems
    columns:
      - name: item_key
        description: PK
        tests:
          - not_null
          - unique

  - name: dim_ga4_doms_geo
    description: table with the unique geo locations from GA, https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cgeo
    columns:
      - name: geo_key
        description: PK
        tests:
          - not_null
          - unique

  - name: dim_ga4_doms_product_master_mapping
    description: Mapping table to the the Miele Product Master that is populated from PIM. dwh.dim_product_master_pim
    columns:
      - name: item_key
        description: link to GA4 fact tables
        tests:
          - unique
      - name: dim_product_master_key
        description: FK, key that links to the Miele product master table, dwh.dim_product_master_pim
        tests:
          - relationships:
              to: source('src_dim_product_master','dim_product_master_pim')
              field: dim_product_master_key


  - name: dim_ga4_doms_session
    description: table with a record for every unique session
    columns:
      - name: session_key
        description: PK, unique combination of 'user_pseudo_id', 'stream_id', 'ga_session_id'
        tests:
          - not_null
          - unique
      - name: ga_session_id
        description: timestamp of when a session began

  - name: dim_ga4_doms_traffic_source
    description: unique combinations of traffic source and medium from collected traffic source in GA   
    colunns:
      - name: traffic_source_key
        description: PK
        tests:
          - not_null
          - unique
      - name: session_source
        tests:
          - not_null
      - name: session_medium
        tests:
          - not_null
      - name: custom_channel_grouping
        description: grouping based on custom logic applied to session_source and session_medium

