version: 2

models:
  - name: dwh_fct_amazon_sales_report
    description: "DWH Table with Amazon SP API sales report data combining the 'Manufacturing' and 'Sourcing' views."
    columns:
      - name: id
        description: "Unique identifier for the row. Hash of vendor, day_date and asin."
        tests:
          - unique
          - not_null

      - name: vendor
        description: "The Amazon SP API Vendor ID (Internal identifier matching country code followed by an counter in case of multiple vendors per country)"
      
      - name: amazon_country
        description: "The Amazon country code"

      - name: vg
        description: "The Miele VG to which this vendor belongs"
        tests:
          - not_null

      - name: marketplace_id
        description: "The technical Amazon Marketplace ID which matches the marketplace for a country"

      - name: report_type
        description: "The type of Amazon SP API report"

      - name: report_period
        description: "The granularity of the report"

      - name: selling_program
        description: "The Amazon Retail Program (In the case of Miele is always 'Retail')"

      - name: asin_code
        description: "The ASIN code for the current row"

      - name: day_date
        description: "The date for the current row"

      - name: report_local_currency
        description: "The local currency for the current row"

      - name: customer_returns_sourcing
        description: "The number of customer returns for this ASIN on this date in sourcing view"

      - name: customer_returns_manufacturing
        description: "The number of customer returns for this ASIN on this date in manufacturing view"

      - name: shipped_cogs_amount_lc_sourcing
        description: "The COGS amount shipped in local currency in sourcing view"

      - name: shipped_cogs_amount_lc_manufacturing
        description: "The COGS amount shipped in local currency in manufacturing view"

      - name: shipped_cogs_amount_eur_sourcing
        description: "The COGS amount shipped in euro in sourcing view"
        tests:
          - not_null

      - name: shipped_cogs_amount_eur_manufacturing
        description: "The COGS amount shipped in euro in manufacturing view"
        tests:
          - not_null

      - name: shipped_revenue_amount_lc_sourcing
        description: "The revenue amount shipped in local currency in sourcing view"

      - name: shipped_revenue_amount_lc_manufacturing
        description: "The revenue amount shipped in local currency in manufacturing view"

      - name: shipped_revenue_amount_eur_sourcing
        description: "The revenue amount shipped in euro in sourcing view"
        tests:
          - not_null

      - name: shipped_revenue_amount_eur_manufacturing
        description: "The revenue amount shipped in euro in manufacturing view"
        tests:
          - not_null

      - name: shipped_units_sourcing
        description: "The number of shipped units in sourcing view"

      - name: shipped_units_manufacturing
        description: "The number of shipped units in manufacturing view"

      - name: ordered_revenue_amount_lc
        description: "The ordered revenue amount in local currency"

      - name: ordered_revenue_amount_eur
        description: "The ordered revenue amount in euro"
        tests:
          - not_null

      - name: ordered_units
        description: "The number of ordered units"

      - name: meta_insert_ts
        description: "The insertion timestamp of the row"

  - name: dwh_fct_amazon_traffic_report
    description: "DWH Table with Amazon SP API traffic report data."
    columns:
      - name: id
        description: "Unique identifier for the row. Hash of vendor, day_date and asin."

      - name: vendor
        description: "The Amazon SP API Vendor ID (Internal identifier matching country code followed by an counter in case of multiple vendors per country)"

      - name: amazon_country
        description: "The Amazon country code"

      - name: vg
        description: "The Miele VG to which this vendor belongs"

      - name: marketplace_id
        description: "The technical Amazon Marketplace ID which matches the marketplace for a country"

      - name: report_type
        description: "The type of Amazon SP API report"

      - name: report_period
        description: "The granularity of the report"

      - name: asin_code
        description: "The ASIN code for the current row"

      - name: day_date
        description: "The date for the current row"

      - name: glance_views
        description: "The number of glance views"

      - name: meta_insert_ts
        description: "The insertion timestamp of the row"

  - name: dwh_fct_amazon_net_pure_product_margin_report
    description: "DWH Table with Amazon SP API net pure product margin report data."
    columns:
      - name: id
        description: "Unique identifier for the row. Hash of vendor, day_date and asin."

      - name: vendor
        description: "The Amazon SP API Vendor ID (Internal identifier matching country code followed by an counter in case of multiple vendors per country)"

      - name: amazon_country
        description: "The Amazon country code"

      - name: vg
        description: "The Miele VG to which this vendor belongs"

      - name: marketplace_id
        description: "The technical Amazon Marketplace ID which matches the marketplace for a country"

      - name: report_type
        description: "The type of Amazon SP API report"

      - name: report_period
        description: "The granularity of the report"

      - name: asin_code
        description: "The ASIN code for the current row"

      - name: day_date
        description: "The date for the current row"

      - name: net_pure_product_margin
        description: "The net pure product margin"

      - name: meta_insert_ts
        description: "The insertion timestamp of the row"
