models:
  - name: fct_ga4_doms_order
    description: contains all purchase events, https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cecommerce
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - transaction_id
            - property_id
    columns:
      - name: order_key
        description: PK
        tests:
          - not_null
          - unique
      - name: date_key
        description: format yyyyMMdd, FK, links to dim_date
        tests:
          - relationships:
              to: source('src_reference','dim_date')
              field: date_key
      - name: session_key
        description: FK, links to dim_session, Surrogate Key based on user_pseudo_id, ga_session_id and stream_id
        tests:
          - relationships:
              to: ref('dim_ga4_doms_session')
              field: session_key
      - name: device_key
        description: FK, links to ga4_doms_dim_device
        tests:
          - relationships:
              to: ref('dim_ga4_doms_device')
              field: device_key
      - name: geo_key
        description: FK, links to ga4_doms_dim_geo
        tests:
          - relationships:
              to: ref('dim_ga4_doms_geo')
              field: geo_key
      - name: traffic_source_key
        description: FK, links to ga4_doms_dim_traffic_source
        tests:
          - relationships:
              to: ref('dim_ga4_doms_traffic_source')
              field: traffic_source_key             
      - name: event_timestamp_local
        description: timestamp of the event in the timezone of the GA property
      - name: event_timestamp_utc
        description: timestamp in utc timezone
      - name: transaction_id
        description: field that identifies an unique transaction/purchase within a property
        tests:
          - not_null
      - name: currency
        description: currency code taken from event parameter
        tests:
          - not_null
      - name: purchase_revenue
        description: Purchase revenue of this event, represented in local currency. No calculation in DDP.
      - name: purchase_revenue_eur
        description: Revenue in euro. Converted with a monthly exchange rate.
      - name: shipping_value
        description: The shipping cost in this event, represented in local currency.
      - name: shipping_value_eur
        description: Value in euro. Converted with a monthly exchange rate.
      - name: tax_value
        description: The tax value in this event, represented in local currency with standard unit.
      - name: tax_value_eur
        description: Value in euro. Converted with a monthly exchange rate.
      - name: refund_value
        description: The amount of refund in this event, represented in local currency. Populated only if a refund event is present.
      - name: refund_value_eur
        description: Value in euro. Converted with a monthly exchange rate.    
      - name: unique_items
        description: The number of unique items in this event, based on item_id, item_name, and item_brand. No calculation in DDP.
      - name: total_item_quantity
        description: Total number of items in this event, which is the sum of items.quantity. No calculation in DDP.
      - name: checkout_type
        description: custom parameter of the purchase event
      - name: order_coupon
        description: The code that the user has redeemed to get a discount applicable to the whole cart or transaction contents (all items get discounted, except those that already have a product-level coupon applied to them)
      - name: order_discount
        description: The total value to be discounted as a result of redeeming a transaction-level coupon.
      - name: overall_discount
        description: The sum of all discounts (coupon values) applied to both products and cart.
      - name: vg
        description: links to mxa_di_reference.dim_vg
        tests:
          - not_null 
          - relationships:
              to: ref('dim_vg')
              field: vg

  - name: fct_ga4_doms_orderline
    description: contains the items included in a purchase event
    columns:
      - name: order_key
        description: FK, links to ga4_doms_fact_order
        tests:
          - not_null
          - relationships:
              to: ref('fct_ga4_doms_order')
              field: order_key
      - name: date_key
        description: format yyyyMMdd, links to dim_date
        tests:
          - relationships:
              to: source('src_reference','dim_date')
              field: date_key
      - name: item_key
        description: FK, links to the dimension that describes the individual items ga4_doms_dim_ga_item and the PIM product master table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_ga4_doms_ga_item')
              field: item_key
          - relationships:
              to: ref('dim_ga4_doms_product_master_mapping')
              field: item_key
      - name: transaction_id
        description: field that identifies an unique transaction/purchase
        tests:
          - not_null
      - name: price
        description: The price of the item in local currency. Originates in GA
      - name: price_eur
        description: Price in euro. Converted with a monthly exchange rate.
      - name: item_revenue
        description: The revenue of this item, calculated as price * quantity. It is populated for purchase events only, in local currency with standard unit.
      - name: item_revenue_eur
        description: Revenue in euro.  Converted with a monthly exchange rate.
      - name: item_refund
        description: The refund value of this item, calculated as price * quantity. It is populated for refund events only, in local currency with standard unit.
      - name: item_refund_eur
        description: Amount in euro. Converted with a monthly exchange rate.
      - name: quantity
        desciption: amount of items for this specific orderline
      - name: coupon
        description: The coupon name/code associated with the item. This field includes as well products that are on sale or discounted temporarily (so 20% off the regular price or similar)
        
  - name: fct_ga4_doms_pageview
    description: contains all pageview events
    columns:
      - name: session_key
        description: FK, links to ga4_doms_dim_session
        tests:
          - relationships:
              to: ref('dim_ga4_doms_session')
              field: session_key
      - name: date_key
        description: FK, links to dim_date, format yyyyMMdd
        tests:
          - relationships:
              to: source('src_reference','dim_date')
              field: date_key
      - name: traffic_source_key
        description: FK, links to ga4_doms_dim_traffic_source
        tests:
          - relationships:
              to: ref('dim_ga4_doms_traffic_source')
              field: traffic_source_key
      - name: page_location
        description: full page url, coming from pageview event parameter.   
      - name: base_url
        description: url without parameters created from full url with custom regex logic as in UA.
      - name: clean_path
        description: value of clean_path parameter of pageview event
      - name: page_type
        description: value of page_type parameter of pageview event
      - name: page_title
        description: value of page_title parameter of pageview event
      - name: page_referrer
        description: value of page_referrer parameter of pageview event
      - name: pageview_order
        description: order of the pageview within a session
      - name: is_landing_pageview
        description: is 1 if pageview is the first in a session, else 0
      - name: is_exit_pageview
        description: is 1 if pageview is last in a session, else 0
      - name: property_id
        description: GA property where this event originates from, FK to dim_ga_property_id
        tests:
          - relationships:
              to: ref('dim_ga_property_id')
              field: property_id

  - name: fct_ga4_doms_session
    description: contains a record for every distinct session and includes session specific measures
    columns:
      - name: session_key
        description: PK, constructed from user_pseudo_id, stream_id and ga_session_id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('dim_ga4_doms_session')
              field: session_key
      - name: date_key
        description: FK, links to dim_date, format yyyyMMdd
        tests:
          - relationships:
              to: source('src_reference','dim_date')
              field: date_key
      - name: device_key
        description: FK, Device associated with first event in the session. links to ga4_doms_dim_device
        tests:
          - relationships:
              to: ref('dim_ga4_doms_device')
              field: device_key
      - name: traffic_source_key
        description: FK, Links to traffic source on a session level
        tests:
          - relationships:
              to: ref('dim_ga4_doms_traffic_source')
              field: traffic_source_key
      - name: ga_campaign_key
        tests:
          - relationships:
              to: ref('dim_ga4_doms_ga_campaign')
              field: ga_campaign_key
      - name: session_start_ts_local
        desciption: Local timestamp of the first event in the session.
      - name: is_session_engaged
        description: Indicator showing if session is engaged. Based on parameter 'session_engaged'. 
      - name: engagement_time
        description: Sum of engagement time of all events in the session. In seconds.
      - name: session_duration
        description: Time between the first and last event in the session. In seconds.
      - name: is_first_visit
        description: Indicator showing if this session is the first session for the registered user. Based on parameter 'ga_session_number'
      - name: device_category
        description: category of the device linked to the first event in the session. (desktop/mobile/tablet/etc.)