{{ config(
    schema = "restricted_pbi_dwh",
    materialized = "view"
) }}
     

with source as (
    select * from {{ ref('fact_sapbw_sales_order_financials') }}
),

renamed as (
    select 
        date_key                                    as `Date Key`,
        date_posting_copa                           as `Date Posting Copa`,
        date_billing                                as `Date Billing`,
        date_good_issue                             as `Date Good Issue`,
        order_number                                as `Order Number`,
        order_line_item                             as `Order Line Item`,
        vg                                          as `VG`,
        reporting_unit_code                         as `Reporting Unit Code`,
        reporting_unit_name                         as `Reporting Unit Name`,
        sales_org                                   as `Sales Org`,
        sales_org_name                              as `Sales Org Name`,
        org_unit                                    as `Org Unit`,
        org_unit_name                               as `Org Unit Name`,
        customer_order_type                         as `Customer Order Type`,
        customer_order_type_name                    as `Customer Order Type Name`,
        sales_group_code                            as `Sales Group Code`,
        sales_group_name                            as `Sales Group Name`,
        crm_transaction_type_code                   as `Crm Transaction Type Code`,
        crm_transaction_type_name                   as `Crm Transaction Type Name`,
        material_code                               as `Material Code`,
        dim_product_master_id                       as `Dim Product Master Id`,
        customer_account_group_code                 as `Customer Account Group Code`,
        customer_account_group_name                 as `Customer Account Group Name`,
        customer_group_code                         as `Customer Group Code `,
        customer_group_name                         as `Customer Group Name`,
        customer_postal_code                        as `Customer Postal Code`,
        customer_association_group_code             as `Customer Association Group Code`,
        customer_association_group_name             as `Customer Association Group Name`,
        customer_soldto_industry_nace_code          as `Customer Soldto Industry Nace Code`,
        customer_soldto_industry_nace_name          as `Customer Soldto Industry Nace Name`,
        customer_soldto_industry_miele_code         as `Customer Soldto Industry Miele Code`,
        customer_soldto_industry_miele_name         as `Customer Soldto Industry Miele Name`,
        customer_soldto_code                        as `Customer Soldto Code`,
        soldto_business_partner_type_code           as `Soldto Business Partner Type Code`,
        soldto_business_partner_type_name           as `Soldto Business Partner Type Name`,
        value_type_code                             as `Value Type Code`,
        value_type_name                             as `Value Type Name`,
        program_series                              as `Program Series`,
        program_series_name                         as `Program Series Name`,
        campaign_code                               as `Campaign Code`,
        campaign_name                               as `Campaign Name`,
        division_sales_code                         as `Division Sales Code`,
        division_sales_name                         as `Division Sales Name`,
        buying_group                                as `Buying Group`,
        buying_group_name                           as `Buying Group Name`,
        org_consumer_classification_chain_code      as `Org Consumer Classification Chain Code`,
        org_consumer_classification_chain_name      as `Org Consumer Classification Chain Name`,
        distribution_channel_code                   as `Distribution Channel Code`,
        distribution_channel_name                   as `Distribution Channel Name`,
        billing_type_code                           as `Billing Type Code`,
        billing_type_name                           as `Billing Type Name`,
        reason_order_code                           as `Reason Order Code`,
        reason_order_name                           as `Reason Order Name`,
        valuation_view                              as `Valuation View`,
        valuation_view_name                         as `Valuation View Name`,
        version_code                                as `Version Code`,
        version_name                                as `Version Name`,
        entry_channel                               as `Entry Channel`,
        entry_channel_name                          as `Entry Channel Name`,
        uom                                         as `Uom        `,
        uom_name                                    as `Uom Name`,
        currency_code                               as `Currency Code`,
        amt_net_sales_inv_II_ext_act                as `Amt Net Sales Inv Ii Ext Act`,
        amt_net_sales_inv_II_ext_act_EUR            as `Amt Net Sales Inv Ii Ext Act Eur`,
        amt_consumer_discount                       as `Amt Consumer Discount`,
        amt_consumer_discount_EUR                   as `Amt Consumer Discount Eur`,
        quantity                                    as `Quantity`,
        quantity_inv_appl_div81                     as `Quantity Inv Appl Div81`,
        quantity_pl_actual_all                      as `Quantity Pl Actual All`,
        is_ecomm                                    as `Is Ecomm`,
        is_individual_consumer                      as `Is Individual Consumer`,
		is_bu_professional                          as `Is BU Professional`	
    from source
    where is_ecomm='Y' or is_bu_professional = 'Y'
)

select * from renamed
