{{ config(
    schema = "restricted_pbi_dwh",
    materialized = "view"
) }}
     

with source as (
    select * from {{ ref('fact_sapbw_sales_order_details') }}
),

renamed as (
    select  
        date_key                                            as `Date Key`,
        date_doc_creation                                   as `Date Doc Creation`,
        date_requested_delivery                             as `Date Requested Delivery`,
        date_confirmed_delivery                             as `Date Confirmed Delivery`,
        date_actual_delivery                                as `Date Actual Delivery`,
        date_document_change                                as `Date Document Change`,
        order_number                                        as `Order Number`,
        order_line_item                                     as `Order Line Item`,
        vg                                                  as `VG`,
        reporting_unit_code                                 as `Reporting Unit Code`,
        reporting_unit_name                                 as `Reporting Unit Name`,
        sales_org                                           as `Sales Org`,
        sales_org_name                                      as `Sales Org Name`,
        org_unit                                            as `Org Unit`,
        org_unit_name                                       as `Org Unit Name`,
        customer_order_type                                 as `Customer Order Type`,
        customer_order_type_name                            as `Customer Order Type Name`,
        sales_doc_type                                      as `Sales Doc Type`,
        sales_doc_type_name                                 as `Sales Doc Type Name`,
        sales_group_code                                    as `Sales Group Code`,
        sales_group_name                                    as `Sales Group Name`,
        document_category_code                              as `Document Category Code`,
        document_category_name                              as `Document Category Name`,
        crm_transaction_type_code                           as `Crm Transaction Type Code`,
        crm_transaction_type_name                           as `Crm Transaction Type Name`,
        material_code                                       as `Material Code`,
        dim_product_master_id                               as `Dim Product Master Id`,
        customer_account_group_code                         as `Customer Account Group Code`,
        customer_account_group_name                         as `Customer Account Group Name`,
        customer_group_code                                 as `Customer Group Code `,
        customer_group_name                                 as `Customer Group Name`,
        customer_postal_code                                as `Customer Postal Code`,
        customer_association_group_code                     as `Customer Association Group Code`,
        customer_association_group_name                     as `Customer Association Group Name`,
        customer_soldto_industry_nace_code                  as `Customer Soldto Industry Nace Code`,
        customer_soldto_industry_nace_name                  as `Customer Soldto Industry Nace Name`,
        customer_soldto_industry_miele_code                 as `Customer Soldto Industry Miele Code`,
        customer_soldto_industry_miele_name                 as `Customer Soldto Industry Miele Name`,
        customer_soldto_code                                as `Customer Soldto Code`,
        soldto_business_partner_type_code                   as `Soldto Business Partner Type Code`,
        soldto_business_partner_type_name                   as `Soldto Business Partner Type Name`,
        soldto_cust_group3_miele_club                       as `Soldto Cust Group3 Miele Club`,
        soldto_cust_group3_miele_club_name                  as `Soldto Cust Group3 Miele Club Name`,
        soldto_internat_acc_customer                        as `Soldto Internat Acc Customer`,
        soldto_internat_acc_customer_name                   as `Soldto Internat Acc Customer Name`,
        campaign_code                                       as `Campaign Code`,
        campaign_name                                       as `Campaign Name`,
        division_sales_code                                 as `Division Sales Code`,
        division_sales_name                                 as `Division Sales Name`,
        item_category_code                                  as `Item Category Code`,
        item_category_name                                  as `Item Category Name`,
        org_consumer_classification_chain_code              as `Org Consumer Classification Chain Code`,
        org_consumer_classification_chain_name              as `Org Consumer Classification Chain Name`,
        distribution_channel_code                           as `Distribution Channel Code`,
        distribution_channel_name                           as `Distribution Channel Name`,
        reason_order_code                                   as `Reason Order Code`,
        reason_order_name                                   as `Reason Order Name`,
        reason_rejection_code                               as `Reason Rejection Code`,
        reason_rejection_name                               as `Reason Rejection Name`,
        entry_channel                                       as `Entry Channel`,
        entry_channel_name                                  as `Entry Channel Name`,
        status_delivered                                    as `Status Delivered`,
        status_delivered_name                               as `Status Delivered Name`,
        status_rejection                                    as `Status Rejection`,
        status_rejection_name                               as `Status Rejection Name`,
        status_system_header                                as `Status System Header`,
        status_system_header_name                           as `Status System Header Name`,
        status_quality                                      as `Status Quality`,
        status_quality_name                                 as `Status Quality Name`,
        project_id                                          as `Project Id`,
        header_item_indicator                               as `Header Item Indicator`,
        valuation_view                                      as `Valuation View`,
        valuation_view_name                                 as `Valuation View Name`,
        value_type_code                                     as `Value Type Code`,
        value_type_name                                     as `Value Type Name`,
        version_code                                        as `Version Code`,
        version_name                                        as `Version Name`,
        program_series                                      as `Program Series`,
        program_series_name                                 as `Program Series Name`,
        dealer_agent                                        as `Dealer Agent`,
        dealer_agent_name                                   as `Dealer Agent Name`,
        buying_group                                        as `Buying Group`,
        buying_group_name                                   as `Buying Group Name`,
        currency_code                                       as `Currency Code`,
        uom                                                 as `Uom`,
        uom_name                                            as `Uom Name`,
        quantity                                            as `Quantity`,
        quantity_uom                                        as `Quantity Uom`,
        quantity_intake                                     as `Quantity Intake`,
        quantity_intake_uom                                 as `Quantity Intake Uom`,
        amt_net_value                                       as `Amt Net Value`,
        amt_net_value_EUR                                   as `Amt Net Value Eur`,
        currency_net_value                                  as `Currency Net Value`,
        amt_net_intake_value                                as `Amt Net Intake Value`,
        amt_net_intake_value_EUR                            as `Amt Net Intake Value Eur`,
        currency_net_intake_value                           as `Currency Net Intake Value`,
        amt_net_price                                       as `Amt Net Price`,
        amt_net_price_EUR                                   as `Amt Net Price Eur`,
        currency_net_price                                  as `Currency Net Price`,
        is_ecomm                                            as `Is Ecomm`,
        is_individual_consumer                              as `Is Individual Consumer`,
		is_bu_professional                                  as `Is BU Professional`		
    from source
    where is_ecomm='Y' or is_bu_professional = 'Y'
)

select * from renamed
