version: 2

models:
  - name: dim_vg
    description: "XXXX"
    tests:
      - dbt_utils.equality:
          tags: data_test
          compare_model: reference.dim_vg
          compare_columns:
            - vg
            - country_name
            - region
            - cluster_name
            - top6
            - large_or_small
            - global_focus_market
            - current_platform_website
            - homepage_url
      - dbt_expectations.expect_table_row_count_to_equal:
          tags: count_test
          value: 50
  - name: dim_country 
    description: "xxxxxx"
    tests:
      - dbt_utils.equality:
          tags: data_test
          compare_model: reference.dim_country
          compare_columns:
            - Country_Name
            - Country_Name_Upper
            - Country_Code2
            - Country_Code3
            - iso_Numeric_code
            - Internet_Country_code
      - dbt_expectations.expect_table_row_count_to_equal:
          tags: count_test
          value: 210

  - name: dim_currency_per_country 
    description: "xxxxxx"
    tests:
      - dbt_utils.equality:
          tags: data_test
          compare_model: reference.dim_currency_per_country
          compare_columns:
            - Country_Name
            - Country_Code2
            - Currency_Name
            - CURRENCY_CODE_ISO
            - Fractional_Unit
            - Currency_to_fu
      - dbt_expectations.expect_table_row_count_to_equal:
          tags: count_test
          value: 199          

  - name: dim_currency 
    description: "xxxxxx"
    tests:
      - dbt_utils.equality:
          tags: data_test
          compare_model: reference.dim_currency
          compare_columns:
            - Currency_code
            - Currency_Name
      - dbt_expectations.expect_table_row_count_to_equal:
          tags: count_test
          value: 150     

  - name: dim_ga_view_id 
    description: "xxxxxx"
    tests:
      - dbt_utils.equality:
          tags: data_test
          compare_model: reference.dim_ga_view_id
          compare_columns:
            - view_id
            - vg
            - vg_ga_name
            - platform_website
            - from_dt
            - to_dt
            - from_dt_yyyymmdd
            - to_dt_yyyymmdd
            - is_active
      - dbt_expectations.expect_table_row_count_to_equal:
          tags: count_test
          value: 65

  - name: ga_traffic_channel_priority 
    description: "xxxxxx"
    tests:
      - dbt_utils.equality:
          tags: data_test
          compare_model: reference.ga_traffic_channel_priority
          compare_columns:
            - traffic_channel
            - priority
      - dbt_expectations.expect_table_row_count_to_equal:
          tags: count_test
          value: 15      
