models:
  - name: enr_ga4_attributed_session_traffic_source
    description: Holds the calculated attributed traffic source for every session.
    columns:
      - name: session_key
        tests: 
          - unique

  - name: enr_ga4_shared_session_logic
    description: Combines the session level logic to be reused in multiple DWH models
    columns:
      - name: session_key
        tests: 
          - not_null
          - unique
      - name: is_consented
        description: A session counts as consented if there is 1 or more consented events in the session. Based on parameter statistical_consent. Values 0,1
        tests:
          - accepted_values:
              values: [0, 1]
      - name: traffic_source_key
        description: Surrogate key composed of session_source and session_medium
      - name: ga_campaign_key
        description: key to link with dim_campaign. Surrogate key based on campaign_id.
      - name: session_source
        description: session attributed traffic source. If gclid present than google/cpc. Otherwise the first valid collected traffic source in the session. If not present than the traffic source of a previous session for the same user.
      - name: session_medium
        description: session attributed traffic source. If gclid present than google/cpc. Otherwise the first valid collected traffic medium in the session. If not present than the traffic source of a previous session for the same user.  
      - name: campaign_id
        description: campaign_id from collected traffic source. Attributed to a session.
